### PR TITLE
[WIP] Cleaned CMake files

### PR DESCRIPTION
**Pull request by diegoferigo**
CMake 3.12 still has some minor issues with the current `master`. The reason is that [`UseSwig.cmake`](https://github.com/Kitware/CMake/blob/master/Modules/UseSWIG.cmake) has been recently refactored.

CMake versions >= 3.8 have new utilities for swig, and it makes sense to start adopting them. However, since we need to support CMake 3.5, the previous logic cannot be entirely removed.

This PR contains the following changes:

- Removed custom `FindMatlab.cmake` (CMake >= 3.5 is more than enough)
- C++11 enforced
- Uses `yarp.i` from the install directory (See #18)

For the time being I tested only generating the bindings and compiling them with octave. I used CMake 3.12.0 and CMake 3.10.2.

### TODO

- Fix install path of additional `.i` files from yarp
- Test matlab
- Test older cmake version (anyone here?)

cc @traversaro @nunoguedelha

### CODE REVIEW

**Comment by nunoguedelha** [comment]
> Test older cmake version (anyone here?)

I have cmake 3.11.4, so I can't test right now an older version.

> Uses yarp.i from the install directory

I can test this within the next couple of days..

**Comment by traversaro** [comment]
I guess just supporting CMake 3.10 is now ok.

**Comment by diegoferigo** [comment]
Accordingly to the tests I did last year when I opened this PR I think is ok, but we should test it again. Most recent CMake version improved the swig integration even further. Fur future reference in [this CMakeLists.txt](https://github.com/robotology/gym-ignition/blob/952c747da7/bindings/CMakeLists.txt) there is a python example with CMake >= 3.12.

**Comment by traversaro** [comment]
Unless someone wants to revive this PR, I suggest to just close it. Even if we want to adopt it, probably it now just make sense to require CMake 3.12, and then directly change  the cmake without all the `if(${CMAKE_VERSION} VERSION_GREATER 3.8)` clauses.

**Comment by diegoferigo** [comment]
Adapting this PR to the new minimum supported CMake version would not be a big task. This PR if I recall simplifies quite a lot the CMake logic, if no one else can dedicate some time in the next few weeks we can close it and reopen it in the future if needed.

**Comment by traversaro** [comment]
> This PR if I recall simplifies quite a lot the CMake logic, if no one else can dedicate some time in the next few weeks we can close it and reopen it in the future if needed.

I do not see any volunteer on the horizon. : )
If someone wants to work on this, feel free to reopen.

**Pull request closed without merging**
