### PR TITLE
Delete FindMatlab.cmake

### PR DESCRIPTION
**Pull request by traversaro**
This ensure that we do not need to manually update MATLAB version for macOS users, as done in https://github.com/robotology/yarp-matlab-bindings/pull/81 . The last time we updated FindMatlab for reason outside adding version mappings is 2016 (see https://github.com/robotology/yarp-matlab-bindings/commit/cf0b0c3b5b4661985ca06483647e4eb6cd0b4032), so I think there should be no problem in this. Conda/homebrew users will get a recent CMake all the time, while apt users should not have problems in using an older FindMatlab.cmake .

### CODE REVIEW

**Comment by lrapetti** [comment]
> Conda/homebrew users will get a recent CMake all the time

Sorry @traversaro, I might be missing a bit of background, but what do you mean by this?

**Comment by traversaro** [comment]
> > Conda/homebrew users will get a recent CMake all the time
> 
> Sorry @traversaro, I might be missing a bit of background, but what do you mean by this?

Both `conda-forge` and `Homebrew` are rolling-release distributions. This means that if one installs `brew install cmake` or `mamba install cmake`, he/she will install the latest CMake (differently from users of Linux distributions such as Ubuntu, in which the CMake version installed by `apt install cmake` is the latest available when the distro was released). So, if a macOS users install a new version of MATLAB and a new version of CMake, with all probability he/she will get a version of FindMatlab from CMake that will be able to deal with the latest Matlab.

**Comment by lrapetti** [comment]
Thanks @traversaro for the clarification! Indeed it makes sense to remove it.

**Comment by traversaro** [comment]
Actually we need to solve https://gitlab.kitware.com/cmake/cmake/-/issues/21912 before deleting FindMatlab .

**Pull request closed without merging**
